import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class AdminDataService {
  // --------------------------------------------------Course Data--------------------------------------------------
  getCourseData(): CourseData[] {
    return [
      {
        id: 1,
        imgSrc: '../../assets/img/WebFundamentals.jpg',
        courseName: 'Web Fundamentals',
        rating: 5,
        instructorName: 'Jonathan',
        participantCount: 50,
        applicantCount: 15,
        progress: 90,
        nextStartDate: '01/03/2024',
        status: 'Seats Filled',
      },
      {
        id: 2,
        imgSrc: '../../assets/img/Git.jpg',
        courseName: 'Git Version Control',
        rating: 5,
        instructorName: 'Maria',
        participantCount: 40,
        applicantCount: 10,
        progress: 90,
        nextStartDate: '01/03/2024',
        status: 'Seats Filled',
      },
      {
        id: 3,
        imgSrc: '../../assets/img/HTML.png',
        courseName: 'HTML Essentials',
        rating: 4,
        instructorName: 'Laura Davis',
        participantCount: 45,
        applicantCount: 15,
        progress: 80,
        nextStartDate: '01/04/2024',
        status: '15 Seats Vacant',
      },
      {
        id: 4,
        imgSrc: '../../assets/img/CSS.png',
        courseName: 'CSS for Web Design',
        rating: 4,
        instructorName: 'David Clark',
        participantCount: 35,
        applicantCount: 20,
        progress: 85,
        nextStartDate: '01/03/2024',
        status: 'Seats Filled',
      },
      {
        id: 5,
        imgSrc: '../../assets/img/Bootstrap.jpg',
        courseName: 'CSS with Bootstrap',
        rating: 5,
        instructorName: 'Emily Anderson',
        participantCount: 45,
        applicantCount: 15,
        progress: 83,
        nextStartDate: '01/03/2024',
        status: '5 Seats Vacant',
      },
      {
        id: 6,
        imgSrc: '../../assets/img/Sass.png',
        courseName: 'CSS with Sass',
        rating: 4,
        instructorName: 'Samuel Evans',
        participantCount: 42,
        applicantCount: 5,
        progress: 80,
        nextStartDate: '01/04/2024',
        status: '10 Seats Vacant',
      },
      {
        id: 7,
        imgSrc: '../../assets/img/AnimationsCSS.jpg',
        courseName: 'CSS Animations',
        rating: 4,
        instructorName: 'Sarah Foster',
        participantCount: 45,
        applicantCount: 10,
        progress: 75,
        nextStartDate: '01/03/2024',
        status: '15 Seats Vacant',
      },
      {
        id: 8,
        imgSrc: '../../assets/img/ResponsiveWebDesign.jpg',
        courseName: 'Responsive Web Design',
        rating: 4,
        instructorName: 'Michael Garcia',
        participantCount: 40,
        applicantCount: 15,
        progress: 70,
        nextStartDate: '01/03/2024',
        status: '10 Seats Vacant',
      },
      {
        id: 9,
        imgSrc: '../../assets/img/JavaScript.jpg',
        courseName: 'JavaScript Fundamentals',
        rating: 4,
        instructorName: 'Rachel Green',
        participantCount: 50,
        applicantCount: 5,
        progress: 50,
        nextStartDate: '01/03/2024',
        status: 'Seats Filled',
      },
      {
        id: 10,
        imgSrc: '../../assets/img/AnimationsJS.jpg',
        courseName: 'JavaScript Animations',
        rating: 4,
        instructorName: 'James Harris',
        participantCount: 25,
        applicantCount: 25,
        progress: 50,
        nextStartDate: '01/03/2024',
        status: '25 Seats Vacant',
      },
      {
        id: 11,
        imgSrc: '../../assets/img/FrontEndFrameworks.jpg',
        courseName: 'Front-End Frameworks',
        rating: 5,
        instructorName: 'Jessica Johnson',
        participantCount: 50,
        applicantCount: 20,
        progress: 75,
        nextStartDate: '01/04/2024',
        status: 'Seats Filled',
      },
      {
        id: 12,
        imgSrc: '../../assets/img/Angular.jpg',
        courseName: 'Angular Fundamentals',
        rating: 4,
        instructorName: 'Matthew Miller',
        participantCount: 30,
        applicantCount: 13,
        progress: 55,
        nextStartDate: '01/04/2024',
        status: '20 Seats Vacant',
      },
      {
        id: 13,
        imgSrc: '../../assets/img/React.jpg',
        courseName: 'React.js Fundamentals',
        rating: 4,
        instructorName: 'Kevin King',
        participantCount: 35,
        applicantCount: 5,
        progress: 65,
        nextStartDate: '01/03/2024',
        status: '15 Seats Vacant',
      },
      {
        id: 14,
        imgSrc: '../../assets/img/Vue.jpg',
        courseName: 'Vue.js Essentials',
        rating: 4,
        instructorName: 'Lisa Martinez',
        participantCount: 40,
        applicantCount: 15,
        progress: 50,
        nextStartDate: '01/03/2024',
        status: 'Seats Filled',
      },
      {
        id: 15,
        imgSrc: '../../assets/img/Node.jpg',
        courseName: 'Node.js Basics',
        rating: 5,
        instructorName: 'Olivia Nelson',
        participantCount: 40,
        applicantCount: 15,
        progress: 50,
        nextStartDate: '01/03/2024',
        status: '20 Seats Vacant',
      },
      {
        id: 16,
        imgSrc: '../../assets/img/TestingDebugging.png',
        courseName: 'Testing and Debugging',
        rating: 5,
        instructorName: 'Jennifer',
        participantCount: 40,
        applicantCount: 15,
        progress: 50,
        nextStartDate: '12/03/2024',
        status: '15 Seats Vacant',
      },
    ];
  }
  // --------------------------------------------------End Course Data--------------------------------------------------

  // --------------------------------------------------Instructor Data--------------------------------------------------
  getInstructorData(): InstructorData[] {
    return [
      {
        id: 1,
        instructorName: 'Maria Campbell',
        rating: 5,
        ongoingCourses: 7,
        upcomingCourses: 4,
      },
      {
        id: 2,
        instructorName: 'Jonathan Baker',
        rating: 4,
        ongoingCourses: 6,
        upcomingCourses: 4,
      },
      {
        id: 3,
        instructorName: 'Laura Davis',
        rating: 5,
        ongoingCourses: 7,
        upcomingCourses: 4,
      },
      {
        id: 4,
        instructorName: 'David Clark',
        rating: 5,
        ongoingCourses: 7,
        upcomingCourses: 5,
      },
      {
        id: 5,
        instructorName: 'Emily Anderson',
        rating: 4,
        ongoingCourses: 6,
        upcomingCourses: 4,
      },
      {
        id: 6,
        instructorName: 'Samuel Evans',
        rating: 4,
        ongoingCourses: 7,
        upcomingCourses: 5,
      },
      {
        id: 7,
        instructorName: 'Sarah Foster',
        rating: 5,
        ongoingCourses: 5,
        upcomingCourses: 4,
      },
      {
        id: 8,
        instructorName: 'Michael Garcia',
        rating: 4,
        ongoingCourses: 6,
        upcomingCourses: 4,
      },
      {
        id: 9,
        instructorName: 'Rachel Green',
        rating: 5,
        ongoingCourses: 7,
        upcomingCourses: 5,
      },
      {
        id: 10,
        instructorName: 'James Harris',
        rating: 5,
        ongoingCourses: 8,
        upcomingCourses: 4,
      },
      {
        id: 11,
        instructorName: 'Jessica Johnson',
        rating: 4,
        ongoingCourses: 7,
        upcomingCourses: 6,
      },
      {
        id: 12,
        instructorName: 'Kevin King',
        rating: 4,
        ongoingCourses: 4,
        upcomingCourses: 4,
      },
      {
        id: 13,
        instructorName: 'Lisa Martinez',
        rating: 5,
        ongoingCourses: 7,
        upcomingCourses: 4,
      },
      {
        id: 14,
        instructorName: 'Matthew Miller',
        rating: 5,
        ongoingCourses: 9,
        upcomingCourses: 5,
      },
      {
        id: 15,
        instructorName: 'Olivia Nelson',
        rating: 4,
        ongoingCourses: 7,
        upcomingCourses: 4,
      },
    ];
  }
  // --------------------------------------------------End of Instructor Data--------------------------------------------------

  // --------------------------------------------------Participant Data--------------------------------------------------
  getParticipantData(): ParticipantData[] {
    return [
      {
        id: 1,
        participantName: 'Samuel Roberts',
        enrolledCourses: 4,
        appliedCourses: 6,
        feedbackSubmitted: 6,
        attendancePercentage: '90%',
        courseRating: 5,
        instructorRating: 5,
        appliedDate: '01/01/2024',
      },
      {
        id: 2,
        participantName: 'Emily Carter',
        enrolledCourses: 5,
        appliedCourses: 4,
        feedbackSubmitted: 10,
        attendancePercentage: '95%',
        courseRating: 4,
        instructorRating: 5,
        appliedDate: '03/03/2024',
      },
      {
        id: 3,
        participantName: 'John Baker',
        enrolledCourses: 7,
        appliedCourses: 6,
        feedbackSubmitted: 7,
        attendancePercentage: '80%',
        courseRating: 5,
        instructorRating: 4,
        appliedDate: '05/01/2024',
      },
      {
        id: 4,
        participantName: 'David Foster',
        enrolledCourses: 4,
        appliedCourses: 6,
        feedbackSubmitted: 5,
        attendancePercentage: '85%',
        courseRating: 4,
        instructorRating: 5,
        appliedDate: '08/01/2024',
      },
      {
        id: 5,
        participantName: 'Michael Davis',
        enrolledCourses: 4,
        appliedCourses: 4,
        feedbackSubmitted: 6,
        attendancePercentage: '90%',
        courseRating: 5,
        instructorRating: 4,
        appliedDate: '10/01/2024',
      },
      {
        id: 6,
        participantName: 'Jessica Evans',
        enrolledCourses: 6,
        appliedCourses: 5,
        feedbackSubmitted: 8,
        attendancePercentage: '70%',
        courseRating: 4,
        instructorRating: 3,
        appliedDate: '11/01/2024',
      },
      {
        id: 7,
        participantName: 'Olivia Green',
        enrolledCourses: 6,
        appliedCourses: 6,
        feedbackSubmitted: 8,
        attendancePercentage: '90%',
        courseRating: 3,
        instructorRating: 4,
        appliedDate: '12/01/2024',
      },
      {
        id: 8,
        participantName: 'Benjamin Harris',
        enrolledCourses: 4,
        appliedCourses: 4,
        feedbackSubmitted: 8,
        attendancePercentage: '65%',
        courseRating: 4,
        instructorRating: 4,
        appliedDate: '14/01/2024',
      },
      {
        id: 9,
        participantName: 'Rachel Jackson',
        enrolledCourses: 6,
        appliedCourses: 5,
        feedbackSubmitted: 9,
        attendancePercentage: '85%',
        courseRating: 5,
        instructorRating: 4,
        appliedDate: '15/01/2024',
      },
      {
        id: 10,
        participantName: 'Daniel King',
        enrolledCourses: 7,
        appliedCourses: 6,
        feedbackSubmitted: 8,
        attendancePercentage: '75%',
        courseRating: 5,
        instructorRating: 5,
        appliedDate: '10/01/2024',
      },
      {
        id: 11,
        participantName: 'Laura Lopez',
        enrolledCourses: 4,
        appliedCourses: 6,
        feedbackSubmitted: 6,
        attendancePercentage: '90%',
        courseRating: 5,
        instructorRating: 5,
        appliedDate: '4/01/2024',
      },
      {
        id: 12,
        participantName: 'Jennifer Nelson',
        enrolledCourses: 4,
        appliedCourses: 6,
        feedbackSubmitted: 8,
        attendancePercentage: '75%',
        courseRating: 5,
        instructorRating: 4,
        appliedDate: '20/01/2024',
      },
      {
        id: 13,
        participantName: 'Matthew Mitchell',
        enrolledCourses: 4,
        appliedCourses: 6,
        feedbackSubmitted: 9,
        attendancePercentage: '90%',
        courseRating: 5,
        instructorRating: 5,
        appliedDate: '25/01/2024',
      },
      {
        id: 14,
        participantName: 'William Parker',
        enrolledCourses: 5,
        appliedCourses: 5,
        feedbackSubmitted: 10,
        attendancePercentage: '80%',
        courseRating: 4,
        instructorRating: 5,
        appliedDate: '28/01/2024',
      },
      {
        id: 15,
        participantName: 'Victoria Ramirez',
        enrolledCourses: 4,
        appliedCourses: 4,
        feedbackSubmitted: 6,
        attendancePercentage: '75%',
        courseRating: 4,
        instructorRating: 4,
        appliedDate: '26/01/2024',
      },
      {
        id: 16,
        participantName: 'Andrew Scott',
        enrolledCourses: 6,
        appliedCourses: 6,
        feedbackSubmitted: 7,
        attendancePercentage: '80%',
        courseRating: 4,
        instructorRating: 4,
        appliedDate: '01/02/2024',
      },
      {
        id: 17,
        participantName: 'Sophia Turner',
        enrolledCourses: 5,
        appliedCourses: 5,
        feedbackSubmitted: 8,
        attendancePercentage: '85%',
        courseRating: 5,
        instructorRating: 4,
        appliedDate: '03/02/2024',
      },
      {
        id: 18,
        participantName: 'Lucas White',
        enrolledCourses: 7,
        appliedCourses: 6,
        feedbackSubmitted: 8,
        attendancePercentage: '70%',
        courseRating: 3,
        instructorRating: 3,
        appliedDate: '05/02/2024',
      },
      {
        id: 19,
        participantName: 'Ella Foster',
        enrolledCourses: 4,
        appliedCourses: 4,
        feedbackSubmitted: 5,
        attendancePercentage: '90%',
        courseRating: 5,
        instructorRating: 5,
        appliedDate: '08/02/2024',
      },
      {
        id: 20,
        participantName: 'Aiden Davis',
        enrolledCourses: 6,
        appliedCourses: 5,
        feedbackSubmitted: 10,
        attendancePercentage: '75%',
        courseRating: 4,
        instructorRating: 4,
        appliedDate: '10/02/2024',
      },
      {
        id: 21,
        participantName: 'Mia Evans',
        enrolledCourses: 4,
        appliedCourses: 4,
        feedbackSubmitted: 6,
        attendancePercentage: '80%',
        courseRating: 5,
        instructorRating: 4,
        appliedDate: '12/02/2024',
      },
      {
        id: 22,
        participantName: 'Jackson Green',
        enrolledCourses: 7,
        appliedCourses: 6,
        feedbackSubmitted: 8,
        attendancePercentage: '85%',
        courseRating: 4,
        instructorRating: 5,
        appliedDate: '14/02/2024',
      },
      {
        id: 23,
        participantName: 'Sophie Harris',
        enrolledCourses: 6,
        appliedCourses: 5,
        feedbackSubmitted: 8,
        attendancePercentage: '90%',
        courseRating: 5,
        instructorRating: 4,
        appliedDate: '16/02/2024',
      },
      {
        id: 24,
        participantName: 'Noah Jackson',
        enrolledCourses: 5,
        appliedCourses: 4,
        feedbackSubmitted: 9,
        attendancePercentage: '70%',
        courseRating: 4,
        instructorRating: 3,
        appliedDate: '18/02/2024',
      },
      {
        id: 25,
        participantName: 'Isabella King',
        enrolledCourses: 4,
        appliedCourses: 4,
        feedbackSubmitted: 8,
        attendancePercentage: '85%',
        courseRating: 5,
        instructorRating: 5,
        appliedDate: '20/02/2024',
      },
      {
        id: 26,
        participantName: 'Liam Lopez',
        enrolledCourses: 6,
        appliedCourses: 5,
        feedbackSubmitted: 6,
        attendancePercentage: '75%',
        courseRating: 4,
        instructorRating: 4,
        appliedDate: '22/02/2024',
      },
      {
        id: 27,
        participantName: 'Ava Martinez',
        enrolledCourses: 7,
        appliedCourses: 6,
        feedbackSubmitted: 5,
        attendancePercentage: '80%',
        courseRating: 3,
        instructorRating: 4,
        appliedDate: '24/02/2024',
      },
      {
        id: 28,
        participantName: 'Oliver Mitchell',
        enrolledCourses: 5,
        appliedCourses: 5,
        feedbackSubmitted: 10,
        attendancePercentage: '90%',
        courseRating: 5,
        instructorRating: 4,
        appliedDate: '26/02/2024',
      },
      {
        id: 29,
        participantName: 'Emma Parker',
        enrolledCourses: 4,
        appliedCourses: 4,
        feedbackSubmitted: 8,
        attendancePercentage: '75%',
        courseRating: 4,
        instructorRating: 5,
        appliedDate: '28/02/2024',
      },
      {
        id: 30,
        participantName: 'Carter Ramirez',
        enrolledCourses: 6,
        appliedCourses: 5,
        feedbackSubmitted: 9,
        attendancePercentage: '85%',
        courseRating: 5,
        instructorRating: 4,
        appliedDate: '02/03/2024',
      },
      {
        id: 31,
        participantName: 'Aubrey Scott',
        enrolledCourses: 7,
        appliedCourses: 6,
        feedbackSubmitted: 8,
        attendancePercentage: '70%',
        courseRating: 4,
        instructorRating: 3,
        appliedDate: '04/03/2024',
      },
      {
        id: 32,
        participantName: 'Grayson Turner',
        enrolledCourses: 5,
        appliedCourses: 4,
        feedbackSubmitted: 6,
        attendancePercentage: '80%',
        courseRating: 3,
        instructorRating: 4,
        appliedDate: '06/03/2024',
      },
      {
        id: 33,
        participantName: 'Aria White',
        enrolledCourses: 4,
        appliedCourses: 4,
        feedbackSubmitted: 8,
        attendancePercentage: '85%',
        courseRating: 5,
        instructorRating: 5,
        appliedDate: '08/03/2024',
      },
      {
        id: 34,
        participantName: 'Elijah Foster',
        enrolledCourses: 6,
        appliedCourses: 5,
        feedbackSubmitted: 5,
        attendancePercentage: '90%',
        courseRating: 4,
        instructorRating: 4,
        appliedDate: '10/03/2024',
      },
      {
        id: 35,
        participantName: 'Scarlett Davis',
        enrolledCourses: 7,
        appliedCourses: 6,
        feedbackSubmitted: 10,
        attendancePercentage: '75%',
        courseRating: 5,
        instructorRating: 5,
        appliedDate: '12/03/2024',
      },
      {
        id: 36,
        participantName: 'Logan Evans',
        enrolledCourses: 5,
        appliedCourses: 5,
        feedbackSubmitted: 8,
        attendancePercentage: '80%',
        courseRating: 4,
        instructorRating: 3,
        appliedDate: '14/03/2024',
      },
      {
        id: 37,
        participantName: 'Layla Green',
        enrolledCourses: 4,
        appliedCourses: 4,
        feedbackSubmitted: 9,
        attendancePercentage: '85%',
        courseRating: 5,
        instructorRating: 4,
        appliedDate: '16/03/2024',
      },
      {
        id: 38,
        participantName: 'Mason Harris',
        enrolledCourses: 6,
        appliedCourses: 5,
        feedbackSubmitted: 8,
        attendancePercentage: '90%',
        courseRating: 5,
        instructorRating: 4,
        appliedDate: '18/03/2024',
      },
      {
        id: 39,
        participantName: 'Zoe Jackson',
        enrolledCourses: 7,
        appliedCourses: 6,
        feedbackSubmitted: 6,
        attendancePercentage: '70%',
        courseRating: 4,
        instructorRating: 3,
        appliedDate: '20/03/2024',
      },
      {
        id: 40,
        participantName: 'Wyatt King',
        enrolledCourses: 5,
        appliedCourses: 4,
        feedbackSubmitted: 8,
        attendancePercentage: '75%',
        courseRating: 5,
        instructorRating: 4,
        appliedDate: '22/03/2024',
      },
      {
        id: 41,
        participantName: 'Alyssa Lopez',
        enrolledCourses: 4,
        appliedCourses: 4,
        feedbackSubmitted: 5,
        attendancePercentage: '80%',
        courseRating: 3,
        instructorRating: 4,
        appliedDate: '24/03/2024',
      },
      {
        id: 42,
        participantName: 'Caleb Martinez',
        enrolledCourses: 6,
        appliedCourses: 5,
        feedbackSubmitted: 10,
        attendancePercentage: '85%',
        courseRating: 5,
        instructorRating: 4,
        appliedDate: '26/03/2024',
      },
      {
        id: 43,
        participantName: 'Madison Mitchell',
        enrolledCourses: 7,
        appliedCourses: 6,
        feedbackSubmitted: 8,
        attendancePercentage: '90%',
        courseRating: 4,
        instructorRating: 5,
        appliedDate: '28/03/2024',
      },
      {
        id: 44,
        participantName: 'Jackson Parker',
        enrolledCourses: 6,
        appliedCourses: 5,
        feedbackSubmitted: 9,
        attendancePercentage: '75%',
        courseRating: 5,
        instructorRating: 5,
        appliedDate: '30/03/2024',
      },
      {
        id: 45,
        participantName: 'Emma Ramirez',
        enrolledCourses: 5,
        appliedCourses: 4,
        feedbackSubmitted: 8,
        attendancePercentage: '70%',
        courseRating: 4,
        instructorRating: 4,
        appliedDate: '01/04/2024',
      },
      {
        id: 46,
        participantName: 'Evan Scott',
        enrolledCourses: 4,
        appliedCourses: 4,
        feedbackSubmitted: 6,
        attendancePercentage: '80%',
        courseRating: 5,
        instructorRating: 5,
        appliedDate: '03/04/2024',
      },
      {
        id: 47,
        participantName: 'Ava Turner',
        enrolledCourses: 6,
        appliedCourses: 5,
        feedbackSubmitted: 5,
        attendancePercentage: '85%',
        courseRating: 4,
        instructorRating: 4,
        appliedDate: '05/04/2024',
      },
      {
        id: 48,
        participantName: 'William White',
        enrolledCourses: 7,
        appliedCourses: 6,
        feedbackSubmitted: 10,
        attendancePercentage: '90%',
        courseRating: 5,
        instructorRating: 5,
        appliedDate: '07/04/2024',
      },
      {
        id: 49,
        participantName: 'Sophia Foster',
        enrolledCourses: 5,
        appliedCourses: 4,
        feedbackSubmitted: 8,
        attendancePercentage: '75%',
        courseRating: 4,
        instructorRating: 4,
        appliedDate: '09/04/2024',
      },
      {
        id: 50,
        participantName: 'Mason Davis',
        enrolledCourses: 4,
        appliedCourses: 4,
        feedbackSubmitted: 8,
        attendancePercentage: '80%',
        courseRating: 5,
        instructorRating: 4,
        appliedDate: '11/04/2024',
      },
    ];
  }
  // --------------------------------------------------End  of Participant Data--------------------------------------------------

  // --------------------------------------------------Applicant Data--------------------------------------------------
  getApplicantData(): ApplicantData[] {
    return [
      { id: 1, applicantName: 'Amanda Scott', appliedDate: '01/01/2024' },
      { id: 2, applicantName: 'Jonathan Turner', appliedDate: '03/02/2024' },
      { id: 3, applicantName: 'Maria White', appliedDate: '05/01/2024' },
      { id: 4, applicantName: 'James Wilson', appliedDate: '08/01/2024' },
      { id: 5, applicantName: 'Kevin Young', appliedDate: '10/01/2024' },
      { id: 6, applicantName: 'Samuel Roberts', appliedDate: '11/01/2024' },
      { id: 7, applicantName: 'Lisa Smith', appliedDate: '12/01/2024' },
      { id: 8, applicantName: 'Samuel Thomas', appliedDate: '14/01/2024' },
      { id: 9, applicantName: 'Rachel Walker', appliedDate: '15/01/2024' },
      { id: 10, applicantName: 'Kimberly Clark', appliedDate: '15/01/2024' },
      { id: 11, applicantName: 'Michael Turner', appliedDate: '20/01/2024' },
      { id: 12, applicantName: 'Emily Harris', appliedDate: '22/01/2024' },
      { id: 13, applicantName: 'David Clark', appliedDate: '25/01/2024' },
      { id: 14, applicantName: 'Olivia Nelson', appliedDate: '28/01/2024' },
      { id: 15, applicantName: 'Jessica Johnson', appliedDate: '01/02/2024' },
      { id: 16, applicantName: 'Matthew Miller', appliedDate: '03/02/2024' },
      { id: 17, applicantName: 'Laura Davis', appliedDate: '05/02/2024' },
      { id: 18, applicantName: 'John Baker', appliedDate: '08/02/2024' },
      { id: 19, applicantName: 'Ella Martinez', appliedDate: '5/02/2024' },
      { id: 20, applicantName: 'Brian Evans', appliedDate: '1/02/2024' },
      { id: 21, applicantName: 'Sophia Turner', appliedDate: '10/02/2024' },
      { id: 22, applicantName: 'Jackson Walker', appliedDate: '12/02/2024' },
      { id: 23, applicantName: 'Ava Wilson', appliedDate: '15/02/2024' },
      { id: 24, applicantName: 'Daniel Young', appliedDate: '20/02/2024' },
      { id: 25, applicantName: 'Grace Roberts', appliedDate: '22/02/2024' },
    ];
  }
  // --------------------------------------------------End of Applicant Data--------------------------------------------------

  // -------------------------Stars as per Rating-------------------------
  getStars(rating: number): number[] {
    let starCntArray = Array.from({ length: rating }, (_, index) => index);
    // console.log('Star Count Array  ---> ', starCntArray);
    return starCntArray;
  }
  // -------------------------End of Stars as per Rating-------------------------

  constructor() {}
}

// --------------------------------------------------Interfaces--------------------------------------------------
// -------------------------Blueprint of Course Data-------------------------
export interface CourseData {
  id: number;
  imgSrc: string;
  courseName: string;
  rating: number;
  instructorName: string;
  participantCount: number;
  applicantCount: number;
  progress: number;
  nextStartDate: string;
  status: string;
}

// -------------------------Blueprint of Instructor Data-------------------------
export interface InstructorData {
  id: number;
  instructorName: string;
  rating: number;
  ongoingCourses: number;
  upcomingCourses: number;
}

// -------------------------Blueprint of Participant Data-------------------------
export interface ParticipantData {
  id: number;
  participantName: string;
  enrolledCourses: number;
  appliedCourses: number;
  feedbackSubmitted: number;
  attendancePercentage: string;
  courseRating: number;
  instructorRating: number;
  appliedDate: string;
}

// -------------------------Blueprint of Applicant Data-------------------------
export interface ApplicantData {
  id: number;
  applicantName: string;
  appliedDate: string;
}
// --------------------------------------------------End of Interfaces--------------------------------------------------
